# Generated by Django 5.0.6 on 2026-04-28 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True)),
                ('inputs', models.JSONField()),
                ('plan', models.JSONField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['client_id', 'status'], name='trips_trip_client__4dc154_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('log_data', models.JSONField()),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.TextField(blank=True, null=True)),
                ('corrections', models.JSONField(blank=True, default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
            options={
                'ordering': ('trip_id', 'log_date'),
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('client_event_id', models.UUIDField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'ordering': ('trip_id', 'sequence_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('trip', 'log_date'), name='trips_uniq_log_per_day'),
        ),
        migrations.AddIndex(
            model_name='tripevent',
            index=models.Index(fields=['trip', 'sequence_number'], name='trips_tripe_trip_id_90f5d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripevent',
            constraint=models.UniqueConstraint(fields=('trip', 'client_event_id'), name='trips_uniq_client_event_per_trip'),
        ),
    ]
